name: Deploy React App to Cloud Run

on:
  push:
    branches: ["master"]

env:
  PROJECT_ID: rapid-strength-464107-g0
  REGION: us-central1
  SERVICE: kwestai
  REPO: kwestai-repo  # name of your Artifact Registry repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # uses GCP service account key stored in GitHub Secrets

    - name: Build and push Docker image
      run: |
        IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}"
        docker build -t "$IMAGE" .
        docker push "$IMAGE"
      env:
        DOCKER_BUILDKIT: 1

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}
        region: ${{ env.REGION }}
        allow-unauthenticated: true